version: '3'
services:
  house-cmu:
    build: HouseSimulator/
    ports:
      - "5051:5050"
  house-mse:
    build: HouseSimulator/
    ports:
      - "5050:5050"
  platform:
    build:
      context: Platform/
      no_cache: true
    depends_on:
      mysql-container:
        condition: service_healthy
      house-cmu:
        condition: service_started
      house-mse:
        condition: service_started
    ports:
      - "8080:8080"
  mysql-container:
    build: Database/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TartanHome
      MYSQL_USER: tartan
      MYSQL_PASSWORD: tartan1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mysql-storage: